version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-insta
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:123456@localhost:5432/my-insta?schema=public
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: my-insta
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
